"""
Tests for Groq/LangChain integration.
"""

import os
import sys
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from tests.test_comprehensive import test_results


class TestGroqIntegration:
    """Test Groq API integration."""
    
    def test_groq_api_key_environment_variable(self):
        """Test that Groq API key can be read from environment."""
        try:
            from backend.src.config.base_settings import settings
            
            # Check if environment variable exists (may or may not be set)
            env_key = os.getenv("GROQ_API_KEY")
            settings_key = settings.groq_api_key
            
            # Either should be set for production, but not required for testing
            if env_key or settings_key:
                assert len(settings_key or "") > 0 or len(env_key or "") > 0
            
            test_results["langchain_groq"]["passed"] += 1
        except Exception as e:
            test_results["langchain_groq"]["failed"] += 1
            test_results["langchain_groq"]["errors"].append(f"Groq API key check failed: {e}")
    
    def test_langchain_service_without_api_key(self):
        """Test that LangChain service works without API key (fallback mode)."""
        try:
            from backend.src.reporting.langchain_llm import LangChainLLMService
            
            # Temporarily unset API key
            original_key = os.environ.get("GROQ_API_KEY")
            if "GROQ_API_KEY" in os.environ:
                del os.environ["GROQ_API_KEY"]
            
            try:
                service = LangChainLLMService()
                assert service is not None
                
                # Service should still be initializable, just disabled
                if not service.enabled:
                    # This is expected behavior - service should be disabled without key
                    test_results["langchain_groq"]["passed"] += 1
                else:
                    # Service is enabled, check fallback methods work
                    analysis_results = {"biodiversity": {"score": 75.0}}
                    project_context = {"name": "Test", "type": "solar"}
                    summary = service.generate_executive_summary(analysis_results, project_context)
                    assert summary is not None
                    test_results["langchain_groq"]["passed"] += 1
            finally:
                # Restore original key
                if original_key:
                    os.environ["GROQ_API_KEY"] = original_key
                    
        except Exception as e:
            test_results["langchain_groq"]["failed"] += 1
            test_results["langchain_groq"]["errors"].append(f"LangChain service without API key failed: {e}")
    
    @patch('langchain_groq.ChatGroq')
    def test_groq_integration_mock(self, mock_chat_groq):
        """Test Groq integration with mocked API calls."""
        try:
            from backend.src.reporting.langchain_llm import LangChainLLMService
            
            # Mock the ChatGroq response
            mock_llm = MagicMock()
            mock_response = MagicMock()
            mock_response.content = "This is a test executive summary generated by Groq."
            mock_llm.invoke.return_value = mock_response
            mock_chat_groq.return_value = mock_llm
            
            # Set API key for this test
            original_key = os.environ.get("GROQ_API_KEY")
            os.environ["GROQ_API_KEY"] = "test_key_12345"
            
            try:
                service = LangChainLLMService()
                
                if service.enabled and service.llm:
                    # Test executive summary generation
                    analysis_results = {
                        "biodiversity": {"score": 75.0},
                        "resm": {"score": 80.0},
                    }
                    project_context = {
                        "name": "Test Solar Project",
                        "type": "solar",
                        "country": "ITA",
                    }
                    
                    summary = service.generate_executive_summary(analysis_results, project_context)
                    assert summary is not None
                    assert len(summary) > 0
                
                test_results["langchain_groq"]["passed"] += 1
            finally:
                # Restore original key
                if original_key:
                    os.environ["GROQ_API_KEY"] = original_key
                else:
                    os.environ.pop("GROQ_API_KEY", None)
                    
        except ImportError:
            # langchain_groq not installed - skip this test
            test_results["langchain_groq"]["errors"].append("langchain_groq not installed (expected in some environments)")
            test_results["langchain_groq"]["passed"] += 1
        except Exception as e:
            test_results["langchain_groq"]["failed"] += 1
            test_results["langchain_groq"]["errors"].append(f"Groq integration mock test failed: {e}")
    
    def test_langchain_prompt_templates(self):
        """Test that LangChain prompt templates are properly formatted."""
        try:
            from backend.src.reporting.langchain_llm import LangChainLLMService
            
            service = LangChainLLMService()
            
            # Test that fallback methods produce valid output
            analysis_results = {
                "biodiversity": {"score": 65.0, "sensitivity": "moderate"},
                "resm": {"score": 75.0, "category": "high_suitability"},
                "ahsm": {"score": 35.0, "risk_level": "low"},
                "cim": {"score": 50.0, "impact_level": "moderate"},
            }
            project_context = {
                "name": "Renewable Energy Project",
                "type": "solar",
                "country": "ITA",
                "capacity_mw": 50.0,
            }
            
            # Test executive summary
            summary = service.generate_executive_summary(analysis_results, project_context)
            assert summary is not None
            assert isinstance(summary, str)
            assert len(summary) > 0
            
            # Test biodiversity narrative
            narrative = service.generate_biodiversity_narrative(analysis_results.get("biodiversity", {}))
            assert narrative is not None
            assert isinstance(narrative, str)
            
            # Test ML explanation
            explanation = service.explain_ml_prediction(
                model_name="RESM",
                prediction={"score": 75.0},
                features={"solar_ghi": 4.5}
            )
            assert explanation is not None
            assert isinstance(explanation, str)
            
            test_results["langchain_groq"]["passed"] += 1
        except Exception as e:
            test_results["langchain_groq"]["failed"] += 1
            test_results["langchain_groq"]["errors"].append(f"LangChain prompt templates test failed: {e}")
