-- Temporal data storage schema for ERA5 and forecast data

CREATE TABLE IF NOT EXISTS temporal_data_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_type TEXT NOT NULL,  -- 'era5', 'forecast', 'observation'
    region_name TEXT,
    bbox GEOMETRY(POLYGON, 4326),  -- Bounding box for the data region
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    variables JSONB,  -- List of variables included
    storage_path TEXT NOT NULL,  -- Path to NetCDF/Parquet file
    resolution_km FLOAT,  -- Spatial resolution in km
    resolution_hours INT,  -- Temporal resolution in hours
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_temporal_data_sources_bbox ON temporal_data_sources USING GIST(bbox);
CREATE INDEX IF NOT EXISTS idx_temporal_data_sources_dates ON temporal_data_sources(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_temporal_data_sources_type ON temporal_data_sources(source_type);

-- Point-level temporal series (extracted from ERA5 for specific coordinates)
CREATE TABLE IF NOT EXISTS temporal_series (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_id UUID REFERENCES temporal_data_sources(id),
    run_id TEXT,  -- Link to analysis run
    lon FLOAT NOT NULL,
    lat FLOAT NOT NULL,
    variable TEXT NOT NULL,  -- 'temperature', 'wind_speed', 'solar_radiation', etc.
    timestamp TIMESTAMPTZ NOT NULL,
    value FLOAT NOT NULL,
    unit TEXT,  -- 'celsius', 'm/s', 'kwh/m2', etc.
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_temporal_series_source ON temporal_series(source_id);
CREATE INDEX IF NOT EXISTS idx_temporal_series_run ON temporal_series(run_id);
CREATE INDEX IF NOT EXISTS idx_temporal_series_location ON temporal_series(lon, lat);
CREATE INDEX IF NOT EXISTS idx_temporal_series_timestamp ON temporal_series(timestamp);
CREATE INDEX IF NOT EXISTS idx_temporal_series_variable ON temporal_series(variable);

-- Forecasts generated by TimesFM or other models
CREATE TABLE IF NOT EXISTS temporal_forecasts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id TEXT NOT NULL,  -- Link to analysis run
    model_name TEXT NOT NULL,  -- 'timesfm', 'prophet', 'lstm', etc.
    model_version TEXT,
    variable TEXT NOT NULL,  -- Variable being forecasted
    forecast_type TEXT NOT NULL,  -- 'energy_yield', 'risk', 'temperature', etc.
    start_timestamp TIMESTAMPTZ NOT NULL,  -- Start of forecast period
    end_timestamp TIMESTAMPTZ NOT NULL,  -- End of forecast period
    horizon_days INT NOT NULL,  -- Forecast horizon in days
    forecast_data JSONB NOT NULL,  -- Time series of forecasted values
    confidence_intervals JSONB,  -- Upper/lower bounds if available
    metrics JSONB,  -- Forecast accuracy metrics if validation data available
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_temporal_forecasts_run ON temporal_forecasts(run_id);
CREATE INDEX IF NOT EXISTS idx_temporal_forecasts_model ON temporal_forecasts(model_name);
CREATE INDEX IF NOT EXISTS idx_temporal_forecasts_variable ON temporal_forecasts(variable);
CREATE INDEX IF NOT EXISTS idx_temporal_forecasts_type ON temporal_forecasts(forecast_type);
CREATE INDEX IF NOT EXISTS idx_temporal_forecasts_timestamp ON temporal_forecasts(start_timestamp, end_timestamp);

-- Climate risk projections (aggregated from forecasts)
CREATE TABLE IF NOT EXISTS climate_risk_projections (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id TEXT NOT NULL,
    risk_type TEXT NOT NULL,  -- 'extreme_heat', 'extreme_cold', 'wind_storm', 'drought', etc.
    risk_metric TEXT NOT NULL,  -- 'frequency', 'severity', 'duration', etc.
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    risk_level TEXT NOT NULL,  -- 'low', 'moderate', 'high', 'extreme'
    risk_score FLOAT,  -- 0-100 risk score
    projection_data JSONB,  -- Detailed risk projections
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_climate_risk_run ON climate_risk_projections(run_id);
CREATE INDEX IF NOT EXISTS idx_climate_risk_type ON climate_risk_projections(risk_type);
CREATE INDEX IF NOT EXISTS idx_climate_risk_level ON climate_risk_projections(risk_level);
CREATE INDEX IF NOT EXISTS idx_climate_risk_period ON climate_risk_projections(period_start, period_end);
